logging:
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
application:
  security:
    jwt:
      secret-key: 0f24cd310e47755764f0ed9914fc9ea12cfe75488a0985efa902c733d773793f